### ISSUE TITLE
Create a Git Tag 

### ISSUE THREAD

**Issue by masacc** [brookinsconsulting/BcLowerCaseUrlAlias#1]
Hello,

could you please create a tag in order not to use "dev-master" reference in our composer.json ?

Thanks

**Comment by masacc** [comment]
up

**Comment by brookinsconsulting** [comment]
Hello @masacc 

Thank you for your support!

We have created a tag for you to use, 'v0.0.2.

You can find it here, https://github.com/brookinsconsulting/BcLowerCaseUrlAlias/releases/tag/v0.0.2

Please test the new tag and let us know how it works for you.

Apologies for our quite late response.

Cheers,
Brookins Consulting

**Comment by masacc** [comment]
Hello @brookinsconsulting  and thank you for creating the tag but unfortunately, this is not a valid composer tag : `Could not parse version constraint v0-0-2: Invalid version string "v0-0-2"`. You should use semver tagging instead : `v0.0.2`

And then it can also be recognized by packagist https://packagist.org/packages/brookinsconsulting/bclowercaseurlaliasbundle

**Comment by brookinsconsulting** [comment]
Hello @masacc 

Thank you again for sharing your problem with the tag created (and for sharing the solution). We have updated the tag as you suggested. We truly hope this helps solve the problem your having.

Cheers,
Brookins Consulting
