### ISSUE TITLE
Composer.json compatibility with eZPlatform

### ISSUE THREAD

**Issue by skrosoft** [brookinsconsulting/BcLowerCaseUrlAlias#3]
Hi @brookinsconsulting 

Could you please make the composer.json file compatible with ezplatform? 

Thank you!

**Comment by brookinsconsulting** [comment]
Hello @skrosoft 

We just recently merged changes which should provide this compatibility.

Please test again and let us know what you think :)

Cheers,
Brookins Consulting

**Comment by skrosoft** [comment]
I don't know why but it doesn't seems to work. I mean, I now could install this bundle on eZ Platform v2 but my URL are still with the same format even after creating o updating contents.

**Comment by brookinsconsulting** [comment]
Hello @skrosoft 

Have you followed the installation instructions configuration warning instructions?

Are you using the new ezplatform admin or the legacy admin?

If your using the legacy admin this might be why your still having problems as the configuration needed for that system is similar but different and quite separate.

If no legacy is involved are you certain the bundle is in your autoloads, also are you certain you have cleared all caches?

We hope this helps.

Cheers,
Brookins Consulting
